influx-test:
    build: .
    links:
        - influx
        - grafana

influx:
    image: influxdb:latest
    ports:
        - "8086:8086"

grafana:
    image: grafana/grafana:latest
    ports:
        - "3000:3000"
